### ISSUE TITLE
does not compile esphome 2025.8.0

### ISSUE THREAD

**Issue by MikhailTeddy** [NicoIIT/esphome-ble_adv_proxy#5]
Compiling .pioenvs/esp32-wroom-32-cp2102-38pin-1/src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp.o
Compiling .pioenvs/esp32-wroom-32-cp2102-38pin-1/src/esphome/components/bluetooth_proxy/bluetooth_connection.cpp.o
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp: In member function 'virtual void esphome::ble_adv_proxy::BleAdvProxy::setup()':
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:64:7: error: 'class esphome::Application' has no member named 'register_text_sensor'; did you mean 'register_sensor'?
   64 |   App.register_text_sensor(&this->sensor_name_);
      |       ^~~~~~~~~~~~~~~~~~~~
      |       register_sensor
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp: In member function 'void esphome::ble_adv_proxy::BleAdvProxy::setup_max_tx_power()':
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:140:3: error: 'esp_power_level_t' was not declared in this scope; did you mean 'esp_log_level_t'?
  140 |   esp_power_level_t lev_init = esp_ble_tx_power_get(ESP_BLE_PWR_TYPE_ADV);
      |   ^~~~~~~~~~~~~~~~~
      |   esp_log_level_t
In file included from src/esphome/components/api/proto.h:5,
                 from src/esphome/components/api/api_pb2.h:8,
                 from src/esphome/components/api/api_server.h:6,
                 from src/esphome/components/api/custom_api_device.h:4,
                 from src/esphome/components/ble_adv_proxy/ble_adv_proxy.h:5,
                 from src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:1:
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:141:83: error: 'lev_init' was not declared in this scope; did you mean 'mem_init'?
  141 |   ESP_LOGD(TAG, "Advertising TX Power enum value (NOT dBm) before max setup: %d", lev_init);
      |                                                                                   ^~~~~~~~
src/esphome/core/log.h:99:100: note: in definition of macro 'esph_log_d'
   99 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_DEBUG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                    ^~~~~~~~~~~
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:141:3: note: in expansion of macro 'ESP_LOGD'
  141 |   ESP_LOGD(TAG, "Advertising TX Power enum value (NOT dBm) before max setup: %d", lev_init);
      |   ^~~~~~~~
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:16:22: error: 'ESP_PWR_LVL_P9' was not declared in this scope
   16 | #define MAX_TX_POWER ESP_PWR_LVL_P9
      |                      ^~~~~~~~~~~~~~
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:143:19: note: in expansion of macro 'MAX_TX_POWER'
  143 |   if (lev_init != MAX_TX_POWER) {
      |                   ^~~~~~~~~~~~
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:145:26: error: 'ESP_BLE_PWR_TYPE_ADV' was not declared in this scope; did you mean 'ESP_BLE_AD_TYPE_URI'?
  145 |     esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, MAX_TX_POWER);
      |                          ^~~~~~~~~~~~~~~~~~~~
      |                          ESP_BLE_AD_TYPE_URI
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:145:5: error: 'esp_ble_tx_power_set' was not declared in this scope; did you mean 'esp_ble_tx_power_phy_t'?
  145 |     esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, MAX_TX_POWER);
      |     ^~~~~~~~~~~~~~~~~~~~
      |     esp_ble_tx_power_phy_t
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:146:22: error: expected ';' before 'lev_final'
  146 |     esp_power_level_t lev_final = esp_ble_tx_power_get(ESP_BLE_PWR_TYPE_ADV);
      |                      ^~~~~~~~~~
      |                      ;
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:147:84: error: 'lev_final' was not declared in this scope
  147 |     ESP_LOGI(TAG, "Advertising TX Power enum value (NOT dBm) after max setup: %d", lev_final);
      |                                                                                    ^~~~~~~~~
src/esphome/core/log.h:112:99: note: in definition of macro 'esph_log_i'
  112 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                   ^~~~~~~~~~~
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:147:5: note: in expansion of macro 'ESP_LOGI'
  147 |     ESP_LOGI(TAG, "Advertising TX Power enum value (NOT dBm) after max setup: %d", lev_final);
      |     ^~~~~~~~
src/esphome/components/api/custom_api_device.h: In instantiation of 'void esphome::api::CustomAPIDevice::fire_homeassistant_event(const std::string&, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&) [with T = void; std::string = std::__cxx11::basic_string<char>]':
src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp:132:33:   required from here
  132 |   this->fire_homeassistant_event(ADV_RECV_EVENT, {{CONF_RAW, std::move(raw)}, {CONF_ORIGIN, std::move(str_mac)}});
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/api/custom_api_device.h:274:19: warning: invalid application of 'sizeof' to a void type [-Wpointer-arith]
  274 |     static_assert(sizeof(T) == 0, "fire_homeassistant_event() requires 'homeassistant_services: true' in the 'api:' "
      |                   ^~~~~~~~~
src/esphome/components/api/custom_api_device.h:274:29: error: static assertion failed: fire_homeassistant_event() requires 'homeassistant_services: true' in the 'api:' section of your YAML configuration
  274 |     static_assert(sizeof(T) == 0, "fire_homeassistant_event() requires 'homeassistant_services: true' in the 'api:' "
      |                   ~~~~~~~~~~^~~~
src/esphome/components/api/custom_api_device.h:274:29: note: the comparison reduces to '(1 == 0)'
*** [.pioenvs/esp32-wroom-32-cp2102-38pin-1/src/esphome/components/ble_adv_proxy/ble_adv_proxy.cpp.o] Error 1
========================= [FAILED] Took 93.93 seconds =========================

**Comment by NicoIIT** [comment]
I just pushed the fixes, should now work with ESPHome 2025.8.0

**Comment by retorquere** [comment]
Can it be the logging stanza has also changed? The https://github.com/NicoIIT/ha-ble-adv issue template says to add logging like

```
logger:
  default: info
  logs:
    custom_components.ble_adv: debug
```

but esphome device builder does not accept the `default: info`, and I also can't find the `default` key in https://esphome.io/components/logger/

**Comment by retorquere** [comment]
Ok I'm sorry but this is an error that occurs in the esphome project specifically because of instruction in the ha integration project. It isn't clear to me in what project this belongs!
